package mnj.mfg.model.services.client;

import mnj.mfg.model.services.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 29 13:12:29 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void populateBundles() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateBundles",null,null);
        return;
    }

    public void setPopUpWhereClause() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setPopUpWhereClause",null,null);
        return;
    }

    public void selectAllLines(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"selectAllLines",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }

    public String getUnitName(String orgId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getUnitName",new String [] {"java.lang.String"},new Object[] {orgId});
        return (String)_ret;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public void populateBundlesRec() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateBundlesRec",null,null);
        return;
    }

    public void setPopUpWhereClauseRec() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setPopUpWhereClauseRec",null,null);
        return;
    }

    public void setPopUpWhereClauseThirdParty() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setPopUpWhereClauseThirdParty",null,null);
        return;
    }

    public void populateBundlesThirdParty() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateBundlesThirdParty",null,null);
        return;
    }

    public String CreateRequisition() {
        Object _ret =
            this.riInvokeExportedMethod(this,"CreateRequisition",null,null);
        return (String)_ret;
    }
}
