package mnj.mfg.model.views;

import java.math.BigDecimal;

import mnj.mfg.model.entities.MnjMfgCutissuanceImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 29 13:56:42 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgCutissuanceViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CreatedBy {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CutAssemId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCutAssemId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCutAssemId((String)value);
            }
        }
        ,
        CutfrmDivisionId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCutfrmDivisionId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCutfrmDivisionId((Number)value);
            }
        }
        ,
        CutissueDt {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCutissueDt();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCutissueDt((Date)value);
            }
        }
        ,
        CutissueId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCutissueId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCutissueId((Number)value);
            }
        }
        ,
        CutissueNo {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCutissueNo();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCutissueNo((String)value);
            }
        }
        ,
        CutjobId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCutjobId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCutjobId((String)value);
            }
        }
        ,
        CuttFromDivid {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCuttFromDivid();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCuttFromDivid((String)value);
            }
        }
        ,
        DivisionId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        FgitemCode {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getFgitemCode();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setFgitemCode((String)value);
            }
        }
        ,
        InseamId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getInseamId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setInseamId((String)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LineNo {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getLineNo();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setLineNo((String)value);
            }
        }
        ,
        LotNumber {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getLotNumber();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setLotNumber((String)value);
            }
        }
        ,
        Obno {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getObno();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setObno((String)value);
            }
        }
        ,
        OeSolineId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getOeSolineId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setOeSolineId((Number)value);
            }
        }
        ,
        PostedStatus {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getPostedStatus();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setPostedStatus((String)value);
            }
        }
        ,
        PostedStatusTmp {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getPostedStatusTmp();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setPostedStatusTmp((String)value);
            }
        }
        ,
        RangeId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getRangeId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setRangeId((Number)value);
            }
        }
        ,
        RangeNumber {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getRangeNumber();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setRangeNumber((Number)value);
            }
        }
        ,
        RangrefNo {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getRangrefNo();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setRangrefNo((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        SalesorderId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        SoLine {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getSoLine();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setSoLine((Number)value);
            }
        }
        ,
        StitchAssemId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getStitchAssemId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setStitchAssemId((String)value);
            }
        }
        ,
        StitchJobId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getStitchJobId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setStitchJobId((String)value);
            }
        }
        ,
        SubInventory {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getSubInventory();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setSubInventory((String)value);
            }
        }
        ,
        TransactionStatus {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getTransactionStatus();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setTransactionStatus((String)value);
            }
        }
        ,
        Description {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getDescription();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        BpoNo {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getBpoNo();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        Buyer {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getBuyer();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setBuyer((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        OrderQty {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getOrderQty();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        BalanceQty {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getBalanceQty();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setBalanceQty((Number)value);
            }
        }
        ,
        Color {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getColor();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        IssueTo {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getIssueTo();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setIssueTo((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        RationNo {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getRationNo();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setRationNo((String)value);
            }
        }
        ,
        DeliveryChallanNo {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getDeliveryChallanNo();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setDeliveryChallanNo((String)value);
            }
        }
        ,
        RefDocNo {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getRefDocNo();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setRefDocNo((String)value);
            }
        }
        ,
        CutNumber {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCutNumber();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCutNumber((String)value);
            }
        }
        ,
        ThirdParty {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getThirdParty();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setThirdParty((String)value);
            }
        }
        ,
        IssueToOrg {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getIssueToOrg();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setIssueToOrg((Number)value);
            }
        }
        ,
        IssueOrgName {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getIssueOrgName();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setIssueOrgName((String)value);
            }
        }
        ,
        ReceiveType {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getReceiveType();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setReceiveType((String)value);
            }
        }
        ,
        RecDocNo {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getRecDocNo();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setRecDocNo((String)value);
            }
        }
        ,
        CurrentStyle {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCurrentStyle();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCurrentStyle((String)value);
            }
        }
        ,
        CurrentSeason {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getCurrentSeason();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setCurrentSeason((String)value);
            }
        }
        ,
        TransactionType {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getTransactionType();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setTransactionType((String)value);
            }
        }
        ,
        SystemId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getSystemId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setSystemId((BigDecimal)value);
            }
        }
        ,
        PocId {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getPocId();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setPocId((String)value);
            }
        }
        ,
        Season {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getSeason();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Style {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getStyle();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Colour {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getColour();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setColour((String)value);
            }
        }
        ,
        Wash {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getWash();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setWash((String)value);
            }
        }
        ,
        OrderNumber {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getOrderNumber();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setOrderNumber((Number)value);
            }
        }
        ,
        LineQtyTotal {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getLineQtyTotal();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setLineQtyTotal((BigDecimal)value);
            }
        }
        ,
        Qty_Total {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getQty_Total();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setQty_Total((Number)value);
            }
        }
        ,
        Issued_Qty_Tot {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getIssued_Qty_Tot();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setIssued_Qty_Tot((Number)value);
            }
        }
        ,
        MnjMfgCutissuanceSzlineView {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getMnjMfgCutissuanceSzlineView();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LineVO {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getLineVO();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SaleOrdersLov1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getSaleOrdersLov1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BuyerVO1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getBuyerVO1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Style1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getStyle1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BPOVo1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getBPOVo1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        STNVo1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getSTNVo1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LineLov1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getLineLov1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        cutLOV1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getcutLOV1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IssueToStitchLov1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getIssueToStitchLov1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        rationPlanLov1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getrationPlanLov1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        operatingUnitsVO1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getoperatingUnitsVO1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RecTypeLoV1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getRecTypeLoV1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SystemIdLov1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getSystemIdLov1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RatioPlanNumberLov1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getRatioPlanNumberLov1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SystemLovOpMiz1 {
            public Object get(MnjMfgCutissuanceViewRowImpl obj) {
                return obj.getSystemLovOpMiz1();
            }

            public void put(MnjMfgCutissuanceViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgCutissuanceViewRowImpl object);

        public abstract void put(MnjMfgCutissuanceViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    // public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();


    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CUTASSEMID = AttributesEnum.CutAssemId.index();
    public static final int CUTFRMDIVISIONID = AttributesEnum.CutfrmDivisionId.index();
    public static final int CUTISSUEDT = AttributesEnum.CutissueDt.index();
    public static final int CUTISSUEID = AttributesEnum.CutissueId.index();
    public static final int CUTISSUENO = AttributesEnum.CutissueNo.index();
    public static final int CUTJOBID = AttributesEnum.CutjobId.index();
    public static final int CUTTFROMDIVID = AttributesEnum.CuttFromDivid.index();
    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int FGITEMCODE = AttributesEnum.FgitemCode.index();
    public static final int INSEAMID = AttributesEnum.InseamId.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int LOTNUMBER = AttributesEnum.LotNumber.index();
    public static final int OBNO = AttributesEnum.Obno.index();
    public static final int OESOLINEID = AttributesEnum.OeSolineId.index();
    public static final int POSTEDSTATUS = AttributesEnum.PostedStatus.index();
    public static final int POSTEDSTATUSTMP = AttributesEnum.PostedStatusTmp.index();
    public static final int RANGEID = AttributesEnum.RangeId.index();
    public static final int RANGENUMBER = AttributesEnum.RangeNumber.index();
    public static final int RANGREFNO = AttributesEnum.RangrefNo.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int SOLINE = AttributesEnum.SoLine.index();
    public static final int STITCHASSEMID = AttributesEnum.StitchAssemId.index();
    public static final int STITCHJOBID = AttributesEnum.StitchJobId.index();
    public static final int SUBINVENTORY = AttributesEnum.SubInventory.index();
    public static final int TRANSACTIONSTATUS = AttributesEnum.TransactionStatus.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int BUYER = AttributesEnum.Buyer.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int BALANCEQTY = AttributesEnum.BalanceQty.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int ISSUETO = AttributesEnum.IssueTo.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int RATIONNO = AttributesEnum.RationNo.index();
    public static final int DELIVERYCHALLANNO = AttributesEnum.DeliveryChallanNo.index();
    public static final int REFDOCNO = AttributesEnum.RefDocNo.index();
    public static final int CUTNUMBER = AttributesEnum.CutNumber.index();
    public static final int THIRDPARTY = AttributesEnum.ThirdParty.index();
    public static final int ISSUETOORG = AttributesEnum.IssueToOrg.index();
    public static final int ISSUEORGNAME = AttributesEnum.IssueOrgName.index();
    public static final int RECEIVETYPE = AttributesEnum.ReceiveType.index();
    public static final int RECDOCNO = AttributesEnum.RecDocNo.index();
    public static final int CURRENTSTYLE = AttributesEnum.CurrentStyle.index();
    public static final int CURRENTSEASON = AttributesEnum.CurrentSeason.index();
    public static final int TRANSACTIONTYPE = AttributesEnum.TransactionType.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int POCID = AttributesEnum.PocId.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int COLOUR = AttributesEnum.Colour.index();
    public static final int WASH = AttributesEnum.Wash.index();
    public static final int ORDERNUMBER = AttributesEnum.OrderNumber.index();
    public static final int LINEQTYTOTAL = AttributesEnum.LineQtyTotal.index();
    public static final int QTY_TOTAL = AttributesEnum.Qty_Total.index();
    public static final int ISSUED_QTY_TOT = AttributesEnum.Issued_Qty_Tot.index();
    public static final int MNJMFGCUTISSUANCESZLINEVIEW = AttributesEnum.MnjMfgCutissuanceSzlineView.index();
    public static final int LINEVO = AttributesEnum.LineVO.index();
    public static final int SALEORDERSLOV1 = AttributesEnum.SaleOrdersLov1.index();
    public static final int BUYERVO1 = AttributesEnum.BuyerVO1.index();
    public static final int STYLE1 = AttributesEnum.Style1.index();
    public static final int BPOVO1 = AttributesEnum.BPOVo1.index();
    public static final int STNVO1 = AttributesEnum.STNVo1.index();
    public static final int LINELOV1 = AttributesEnum.LineLov1.index();
    public static final int CUTLOV1 = AttributesEnum.cutLOV1.index();
    public static final int ISSUETOSTITCHLOV1 = AttributesEnum.IssueToStitchLov1.index();
    public static final int RATIONPLANLOV1 = AttributesEnum.rationPlanLov1.index();
    public static final int OPERATINGUNITSVO1 = AttributesEnum.operatingUnitsVO1.index();
    public static final int RECTYPELOV1 = AttributesEnum.RecTypeLoV1.index();
    public static final int SYSTEMIDLOV1 = AttributesEnum.SystemIdLov1.index();
    public static final int RATIOPLANNUMBERLOV1 = AttributesEnum.RatioPlanNumberLov1.index();
    public static final int SYSTEMLOVOPMIZ1 = AttributesEnum.SystemLovOpMiz1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgCutissuanceViewRowImpl() {
    }

    /**
     * Gets MnjMfgCutissuance entity object.
     * @return the MnjMfgCutissuance
     */
    public MnjMfgCutissuanceImpl getMnjMfgCutissuance() {
        return (MnjMfgCutissuanceImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CUT_ASSEM_ID using the alias name CutAssemId.
     * @return the CUT_ASSEM_ID
     */
    public String getCutAssemId() {
        return (String) getAttributeInternal(CUTASSEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUT_ASSEM_ID using the alias name CutAssemId.
     * @param value value to set the CUT_ASSEM_ID
     */
    public void setCutAssemId(String value) {
        setAttributeInternal(CUTASSEMID, value);
    }

    /**
     * Gets the attribute value for CUTFRM_DIVISION_ID using the alias name CutfrmDivisionId.
     * @return the CUTFRM_DIVISION_ID
     */
    public Number getCutfrmDivisionId() {
        return (Number) getAttributeInternal(CUTFRMDIVISIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTFRM_DIVISION_ID using the alias name CutfrmDivisionId.
     * @param value value to set the CUTFRM_DIVISION_ID
     */
    public void setCutfrmDivisionId(Number value) {
        setAttributeInternal(CUTFRMDIVISIONID, value);
    }

    /**
     * Gets the attribute value for CUTISSUE_DT using the alias name CutissueDt.
     * @return the CUTISSUE_DT
     */
    public Date getCutissueDt() {
        return (Date) getAttributeInternal(CUTISSUEDT);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTISSUE_DT using the alias name CutissueDt.
     * @param value value to set the CUTISSUE_DT
     */
    public void setCutissueDt(Date value) {
        setAttributeInternal(CUTISSUEDT, value);
    }

    /**
     * Gets the attribute value for CUTISSUE_ID using the alias name CutissueId.
     * @return the CUTISSUE_ID
     */
    public Number getCutissueId() {
        return (Number) getAttributeInternal(CUTISSUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTISSUE_ID using the alias name CutissueId.
     * @param value value to set the CUTISSUE_ID
     */
    public void setCutissueId(Number value) {
        setAttributeInternal(CUTISSUEID, value);
    }

    /**
     * Gets the attribute value for CUTISSUE_NO using the alias name CutissueNo.
     * @return the CUTISSUE_NO
     */
    public String getCutissueNo() {
        return (String) getAttributeInternal(CUTISSUENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTISSUE_NO using the alias name CutissueNo.
     * @param value value to set the CUTISSUE_NO
     */
    public void setCutissueNo(String value) {
        setAttributeInternal(CUTISSUENO, value);
    }

    /**
     * Gets the attribute value for CUTJOB_ID using the alias name CutjobId.
     * @return the CUTJOB_ID
     */
    public String getCutjobId() {
        return (String) getAttributeInternal(CUTJOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTJOB_ID using the alias name CutjobId.
     * @param value value to set the CUTJOB_ID
     */
    public void setCutjobId(String value) {
        setAttributeInternal(CUTJOBID, value);
    }

    /**
     * Gets the attribute value for CUTT_FROM_DIVID using the alias name CuttFromDivid.
     * @return the CUTT_FROM_DIVID
     */
    public String getCuttFromDivid() {
        return (String) getAttributeInternal(CUTTFROMDIVID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTT_FROM_DIVID using the alias name CuttFromDivid.
     * @param value value to set the CUTT_FROM_DIVID
     */
    public void setCuttFromDivid(String value) {
        setAttributeInternal(CUTTFROMDIVID, value);
    }

    /**
     * Gets the attribute value for DIVISION_ID using the alias name DivisionId.
     * @return the DIVISION_ID
     */
    public String getDivisionId() {
        return (String) getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION_ID using the alias name DivisionId.
     * @param value value to set the DIVISION_ID
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for FGITEM_CODE using the alias name FgitemCode.
     * @return the FGITEM_CODE
     */
    public String getFgitemCode() {
        return (String) getAttributeInternal(FGITEMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for FGITEM_CODE using the alias name FgitemCode.
     * @param value value to set the FGITEM_CODE
     */
    public void setFgitemCode(String value) {
        setAttributeInternal(FGITEMCODE, value);
    }

    /**
     * Gets the attribute value for INSEAM_ID using the alias name InseamId.
     * @return the INSEAM_ID
     */
    public String getInseamId() {
        return (String) getAttributeInternal(INSEAMID);
    }

    /**
     * Sets <code>value</code> as attribute value for INSEAM_ID using the alias name InseamId.
     * @param value value to set the INSEAM_ID
     */
    public void setInseamId(String value) {
        setAttributeInternal(INSEAMID, value);
    }

    /**
     * Gets the attribute value for INVENTORY_ITEM_ID using the alias name InventoryItemId.
     * @return the INVENTORY_ITEM_ID
     */
    public Number getInventoryItemId() {
        return (Number) getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for INVENTORY_ITEM_ID using the alias name InventoryItemId.
     * @param value value to set the INVENTORY_ITEM_ID
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LINE_NO using the alias name LineNo.
     * @return the LINE_NO
     */
    public String getLineNo() {
        return (String) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NO using the alias name LineNo.
     * @param value value to set the LINE_NO
     */
    public void setLineNo(String value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for LOT_NUMBER using the alias name LotNumber.
     * @return the LOT_NUMBER
     */
    public String getLotNumber() {
        return (String) getAttributeInternal(LOTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for LOT_NUMBER using the alias name LotNumber.
     * @param value value to set the LOT_NUMBER
     */
    public void setLotNumber(String value) {
        setAttributeInternal(LOTNUMBER, value);
    }

    /**
     * Gets the attribute value for OBNO using the alias name Obno.
     * @return the OBNO
     */
    public String getObno() {
        return (String) getAttributeInternal(OBNO);
    }

    /**
     * Sets <code>value</code> as attribute value for OBNO using the alias name Obno.
     * @param value value to set the OBNO
     */
    public void setObno(String value) {
        setAttributeInternal(OBNO, value);
    }

    /**
     * Gets the attribute value for OE_SOLINE_ID using the alias name OeSolineId.
     * @return the OE_SOLINE_ID
     */
    public Number getOeSolineId() {
        return (Number) getAttributeInternal(OESOLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for OE_SOLINE_ID using the alias name OeSolineId.
     * @param value value to set the OE_SOLINE_ID
     */
    public void setOeSolineId(Number value) {
        setAttributeInternal(OESOLINEID, value);
    }

    /**
     * Gets the attribute value for POSTED_STATUS using the alias name PostedStatus.
     * @return the POSTED_STATUS
     */
    public String getPostedStatus() {
        return (String) getAttributeInternal(POSTEDSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED_STATUS using the alias name PostedStatus.
     * @param value value to set the POSTED_STATUS
     */
    public void setPostedStatus(String value) {
        setAttributeInternal(POSTEDSTATUS, value);
    }

    /**
     * Gets the attribute value for POSTED_STATUS_TMP using the alias name PostedStatusTmp.
     * @return the POSTED_STATUS_TMP
     */
    public String getPostedStatusTmp() {
        return (String) getAttributeInternal(POSTEDSTATUSTMP);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED_STATUS_TMP using the alias name PostedStatusTmp.
     * @param value value to set the POSTED_STATUS_TMP
     */
    public void setPostedStatusTmp(String value) {
        setAttributeInternal(POSTEDSTATUSTMP, value);
    }

    /**
     * Gets the attribute value for RANGE_ID using the alias name RangeId.
     * @return the RANGE_ID
     */
    public Number getRangeId() {
        return (Number) getAttributeInternal(RANGEID);
    }

    /**
     * Sets <code>value</code> as attribute value for RANGE_ID using the alias name RangeId.
     * @param value value to set the RANGE_ID
     */
    public void setRangeId(Number value) {
        setAttributeInternal(RANGEID, value);
    }

    /**
     * Gets the attribute value for RANGE_NUMBER using the alias name RangeNumber.
     * @return the RANGE_NUMBER
     */
    public Number getRangeNumber() {
        return (Number) getAttributeInternal(RANGENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for RANGE_NUMBER using the alias name RangeNumber.
     * @param value value to set the RANGE_NUMBER
     */
    public void setRangeNumber(Number value) {
        setAttributeInternal(RANGENUMBER, value);
    }

    /**
     * Gets the attribute value for RANGREF_NO using the alias name RangrefNo.
     * @return the RANGREF_NO
     */
    public String getRangrefNo() {
        return (String) getAttributeInternal(RANGREFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RANGREF_NO using the alias name RangrefNo.
     * @param value value to set the RANGREF_NO
     */
    public void setRangrefNo(String value) {
        setAttributeInternal(RANGREFNO, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @return the SALESORDER_ID
     */
    public Number getSalesorderId() {
        return (Number) getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @param value value to set the SALESORDER_ID
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SO_LINE using the alias name SoLine.
     * @return the SO_LINE
     */
    public Number getSoLine() {
        return (Number) getAttributeInternal(SOLINE);
    }

    /**
     * Sets <code>value</code> as attribute value for SO_LINE using the alias name SoLine.
     * @param value value to set the SO_LINE
     */
    public void setSoLine(Number value) {
        setAttributeInternal(SOLINE, value);
    }

    /**
     * Gets the attribute value for STITCH_ASSEM_ID using the alias name StitchAssemId.
     * @return the STITCH_ASSEM_ID
     */
    public String getStitchAssemId() {
        return (String) getAttributeInternal(STITCHASSEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCH_ASSEM_ID using the alias name StitchAssemId.
     * @param value value to set the STITCH_ASSEM_ID
     */
    public void setStitchAssemId(String value) {
        setAttributeInternal(STITCHASSEMID, value);
    }

    /**
     * Gets the attribute value for STITCH_JOB_ID using the alias name StitchJobId.
     * @return the STITCH_JOB_ID
     */
    public String getStitchJobId() {
        return (String) getAttributeInternal(STITCHJOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCH_JOB_ID using the alias name StitchJobId.
     * @param value value to set the STITCH_JOB_ID
     */
    public void setStitchJobId(String value) {
        setAttributeInternal(STITCHJOBID, value);
    }

    /**
     * Gets the attribute value for SUB_INVENTORY using the alias name SubInventory.
     * @return the SUB_INVENTORY
     */
    public String getSubInventory() {
        return (String) getAttributeInternal(SUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_INVENTORY using the alias name SubInventory.
     * @param value value to set the SUB_INVENTORY
     */
    public void setSubInventory(String value) {
        setAttributeInternal(SUBINVENTORY, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_STATUS using the alias name TransactionStatus.
     * @return the TRANSACTION_STATUS
     */
    public String getTransactionStatus() {
        return (String) getAttributeInternal(TRANSACTIONSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_STATUS using the alias name TransactionStatus.
     * @param value value to set the TRANSACTION_STATUS
     */
    public void setTransactionStatus(String value) {
        setAttributeInternal(TRANSACTIONSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for BPO_NO using the alias name BpoNo.
     * @return the BPO_NO
     */
    public String getBpoNo() {
        return (String) getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_NO using the alias name BpoNo.
     * @param value value to set the BPO_NO
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for STYLE using the alias name Style.
     * @return the STYLE
     */
   //undo

    /**
     * Gets the attribute value for the calculated attribute Buyer.
     * @return the Buyer
     */
    public String getBuyer() {
        return (String) getAttributeInternal(BUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Buyer.
     * @param value value to set the  Buyer
     */
    public void setBuyer(String value) {
        setAttributeInternal(BUYER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderNumber.
     * @return the OrderNumber
     */
    public Number getOrderNumber() {
        return (Number) getAttributeInternal(ORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderNumber.
     * @param value value to set the  OrderNumber
     */
    public void setOrderNumber(Number value) {
        setAttributeInternal(ORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LineQtyTotal.
     * @return the LineQtyTotal
     */
    public BigDecimal getLineQtyTotal() {
        return (BigDecimal) getAttributeInternal(LINEQTYTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LineQtyTotal.
     * @param value value to set the  LineQtyTotal
     */
    public void setLineQtyTotal(BigDecimal value) {
        setAttributeInternal(LINEQTYTOTAL, value);
    }

    /**
     * Gets the attribute value for RECEIVE_TYPE using the alias name ReceiveType.
     * @return the RECEIVE_TYPE
     */
    public String getReceiveType() {
        return (String) getAttributeInternal(RECEIVETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVE_TYPE using the alias name ReceiveType.
     * @param value value to set the RECEIVE_TYPE
     */
    public void setReceiveType(String value) {
        setAttributeInternal(RECEIVETYPE, value);
    }

    /**
     * Gets the attribute value for REC_DOC_NO using the alias name RecDocNo.
     * @return the REC_DOC_NO
     */
    public String getRecDocNo() {
        return (String) getAttributeInternal(RECDOCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REC_DOC_NO using the alias name RecDocNo.
     * @param value value to set the REC_DOC_NO
     */
    public void setRecDocNo(String value) {
        setAttributeInternal(RECDOCNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyle.
     * @return the CurrentStyle
     */
    public String getCurrentStyle() {
        return (String) getAttributeInternal(CURRENTSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyle.
     * @param value value to set the  CurrentStyle
     */
    public void setCurrentStyle(String value) {
        setAttributeInternal(CURRENTSTYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentSeason.
     * @return the CurrentSeason
     */
    public String getCurrentSeason() {
        return (String) getAttributeInternal(CURRENTSEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentSeason.
     * @param value value to set the  CurrentSeason
     */
    public void setCurrentSeason(String value) {
        setAttributeInternal(CURRENTSEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransactionType.
     * @return the TransactionType
     */
    public String getTransactionType() {
        return (String) getAttributeInternal(TRANSACTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransactionType.
     * @param value value to set the  TransactionType
     */
    public void setTransactionType(String value) {
        setAttributeInternal(TRANSACTIONTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Qty_Total.
     * @return the Qty_Total
     */
    public Number getQty_Total() {
        return (Number) getAttributeInternal(QTY_TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Qty_Total.
     * @param value value to set the  Qty_Total
     */
    public void setQty_Total(Number value) {
        setAttributeInternal(QTY_TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Issued_Qty_Tot.
     * @return the Issued_Qty_Tot
     */
    public Number getIssued_Qty_Tot() {
        return (Number) getAttributeInternal(ISSUED_QTY_TOT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Issued_Qty_Tot.
     * @param value value to set the  Issued_Qty_Tot
     */
    public void setIssued_Qty_Tot(Number value) {
        setAttributeInternal(ISSUED_QTY_TOT, value);
    }

    /**
     * Gets the attribute value for SYSTEM_ID using the alias name SystemId.
     * @return the SYSTEM_ID
     */
    public BigDecimal getSystemId() {
        return (BigDecimal) getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for SYSTEM_ID using the alias name SystemId.
     * @param value value to set the SYSTEM_ID
     */
    public void setSystemId(BigDecimal value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PocId.
     * @return the PocId
     */
    public String getPocId() {
        return (String) getAttributeInternal(POCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PocId.
     * @param value value to set the  PocId
     */
    public void setPocId(String value) {
        setAttributeInternal(POCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Style.
     * @return the Style
     */
    public String getStyle() {
        return (String) getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Style.
     * @param value value to set the  Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Colour.
     * @return the Colour
     */
    public String getColour() {
        return (String) getAttributeInternal(COLOUR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Colour.
     * @param value value to set the  Colour
     */
    public void setColour(String value) {
        setAttributeInternal(COLOUR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Wash.
     * @return the Wash
     */
    public String getWash() {
        return (String) getAttributeInternal(WASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Wash.
     * @param value value to set the  Wash
     */
    public void setWash(String value) {
        setAttributeInternal(WASH, value);
    }


    /**
     * Gets the attribute value for ISSUE_TO_ORG using the alias name IssueToOrg.
     * @return the ISSUE_TO_ORG
     */
    public Number getIssueToOrg() {
        return (Number) getAttributeInternal(ISSUETOORG);
    }

    /**
     * Sets <code>value</code> as attribute value for ISSUE_TO_ORG using the alias name IssueToOrg.
     * @param value value to set the ISSUE_TO_ORG
     */
    public void setIssueToOrg(Number value) {
        setAttributeInternal(ISSUETOORG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IssueOrgName.
     * @return the IssueOrgName
     */
    public String getIssueOrgName() {
        return (String) getAttributeInternal(ISSUEORGNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IssueOrgName.
     * @param value value to set the  IssueOrgName
     */
    public void setIssueOrgName(String value) {
        setAttributeInternal(ISSUEORGNAME, value);
    }

    /**
     * Gets the attribute value for THIRD_PARTY using the alias name ThirdParty.
     * @return the THIRD_PARTY
     */
    public String getThirdParty() {
        return (String) getAttributeInternal(THIRDPARTY);
    }

    /**
     * Sets <code>value</code> as attribute value for THIRD_PARTY using the alias name ThirdParty.
     * @param value value to set the THIRD_PARTY
     */
    public void setThirdParty(String value) {
        setAttributeInternal(THIRDPARTY, value);
    }

    /**
     * Gets the attribute value for BUYER_ID using the alias name BuyerId.
     * @return the BUYER_ID
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUYER_ID using the alias name BuyerId.
     * @param value value to set the BUYER_ID
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for ORDER_QTY using the alias name OrderQty.
     * @return the ORDER_QTY
     */
    public Number getOrderQty() {
        return (Number) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_QTY using the alias name OrderQty.
     * @param value value to set the ORDER_QTY
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalanceQty.
     * @return the BalanceQty
     */
    public Number getBalanceQty() {
        return (Number) getAttributeInternal(BALANCEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalanceQty.
     * @param value value to set the  BalanceQty
     */
    public void setBalanceQty(Number value) {
        setAttributeInternal(BALANCEQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
  //UNDo


    /**
     * Gets the attribute value for the calculated attribute Color.
     * @return the Color
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Color.
     * @param value value to set the  Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for ISSUE_TO using the alias name IssueTo.
     * @return the ISSUE_TO
     */
    public String getIssueTo() {
        return (String) getAttributeInternal(ISSUETO);
    }

    /**
     * Sets <code>value</code> as attribute value for ISSUE_TO using the alias name IssueTo.
     * @param value value to set the ISSUE_TO
     */
    public void setIssueTo(String value) {
        setAttributeInternal(ISSUETO, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

//    /**
//     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
//     * @return the ATTRIBUTE1
//     */
////    public String getAttribute1() {
////        return (String) getAttributeInternal(ATTRIBUTE1);
////    }
////
////    /**
////     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
////     * @param value value to set the ATTRIBUTE1
////     */
//    public void setAttribute1(String value) {
//        setAttributeInternal(ATTRIBUTE1, value);
//    }

    /**
     * Gets the attribute value for the calculated attribute RationNo.
     * @return the RationNo
     */
    public String getRationNo() {
        return (String) getAttributeInternal(RATIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RationNo.
     * @param value value to set the  RationNo
     */
    public void setRationNo(String value) {
        setAttributeInternal(RATIONNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DeliveryChallanNo.
     * @return the DeliveryChallanNo
     */
    public String getDeliveryChallanNo() {
        return (String) getAttributeInternal(DELIVERYCHALLANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DeliveryChallanNo.
     * @param value value to set the  DeliveryChallanNo
     */
    public void setDeliveryChallanNo(String value) {
        setAttributeInternal(DELIVERYCHALLANNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RefDocNo.
     * @return the RefDocNo
     */
    public String getRefDocNo() {
        return (String) getAttributeInternal(REFDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RefDocNo.
     * @param value value to set the  RefDocNo
     */
    public void setRefDocNo(String value) {
        setAttributeInternal(REFDOCNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CutNumber.
     * @return the CutNumber
     */
    public String getCutNumber() {
        return (String) getAttributeInternal(CUTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CutNumber.
     * @param value value to set the  CutNumber
     */
    public void setCutNumber(String value) {
        setAttributeInternal(CUTNUMBER, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjMfgCutissuanceSzlineView.
     */
    public RowIterator getMnjMfgCutissuanceSzlineView() {
        return (RowIterator)getAttributeInternal(MNJMFGCUTISSUANCESZLINEVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link LineVO.
     */
    public RowIterator getLineVO() {
        return (RowIterator)getAttributeInternal(LINEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SaleOrdersLov1.
     */
    public RowSet getSaleOrdersLov1() {
        return (RowSet)getAttributeInternal(SALEORDERSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BuyerVO1.
     */
    public RowSet getBuyerVO1() {
        return (RowSet)getAttributeInternal(BUYERVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Style1.
     */
    public RowSet getStyle1() {
        return (RowSet)getAttributeInternal(STYLE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BPOVo1.
     */
    public RowSet getBPOVo1() {
        return (RowSet)getAttributeInternal(BPOVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> STNVo1.
     */
    public RowSet getSTNVo1() {
        return (RowSet)getAttributeInternal(STNVO1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> LineLov1.
     */
    public RowSet getLineLov1() {
        return (RowSet)getAttributeInternal(LINELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> cutLOV1.
     */
    public RowSet getcutLOV1() {
        return (RowSet)getAttributeInternal(CUTLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> IssueToStitchLov1.
     */
    public RowSet getIssueToStitchLov1() {
        return (RowSet)getAttributeInternal(ISSUETOSTITCHLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> rationPlanLov1.
     */
    public RowSet getrationPlanLov1() {
        return (RowSet)getAttributeInternal(RATIONPLANLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> operatingUnitsVO1.
     */
    public RowSet getoperatingUnitsVO1() {
        return (RowSet)getAttributeInternal(OPERATINGUNITSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RecTypeLoV1.
     */
    public RowSet getRecTypeLoV1() {
        return (RowSet)getAttributeInternal(RECTYPELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SystemIdLov1.
     */
    public RowSet getSystemIdLov1() {
        return (RowSet)getAttributeInternal(SYSTEMIDLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RatioPlanNumberLov1.
     */
    public RowSet getRatioPlanNumberLov1() {
        return (RowSet)getAttributeInternal(RATIOPLANNUMBERLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SystemLovOpMiz1.
     */
    public RowSet getSystemLovOpMiz1() {
        return (RowSet)getAttributeInternal(SYSTEMLOVOPMIZ1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
