package mnj.mfg.model.views;

import mnj.mfg.model.entities.MnjMfgCutissuanceSzlineImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 29 13:57:30 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgCutissuanceSzlineViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        CutissueId {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getCutissueId();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setCutissueId((Number)value);
            }
        }
        ,
        CutissueNo {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getCutissueNo();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setCutissueNo((Number)value);
            }
        }
        ,
        SzlineNo {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getSzlineNo();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setSzlineNo((Number)value);
            }
        }
        ,
        SizeId {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getSizeId();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setSizeId((String)value);
            }
        }
        ,
        BandelNo {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getBandelNo();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setBandelNo((String)value);
            }
        }
        ,
        ShadeId {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getShadeId();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setShadeId((String)value);
            }
        }
        ,
        SizBndId {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getSizBndId();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setSizBndId((String)value);
            }
        }
        ,
        PlyFrom {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getPlyFrom();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setPlyFrom((Number)value);
            }
        }
        ,
        PlyTo {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getPlyTo();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setPlyTo((Number)value);
            }
        }
        ,
        IssQuantity {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getIssQuantity();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setIssQuantity((Number)value);
            }
        }
        ,
        SrqNumberFrm {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getSrqNumberFrm();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setSrqNumberFrm((Number)value);
            }
        }
        ,
        SrqNumberTo {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getSrqNumberTo();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setSrqNumberTo((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        TransferQty {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getTransferQty();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setTransferQty((Number)value);
            }
        }
        ,
        TotalQty {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getTotalQty();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setTotalQty((Number)value);
            }
        }
        ,
        BalanceQty {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getBalanceQty();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setBalanceQty((Number)value);
            }
        }
        ,
        CutissueLineId {
            public Object get(MnjMfgCutissuanceSzlineViewRowImpl obj) {
                return obj.getCutissueLineId();
            }

            public void put(MnjMfgCutissuanceSzlineViewRowImpl obj,
                            Object value) {
                obj.setCutissueLineId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgCutissuanceSzlineViewRowImpl object);

        public abstract void put(MnjMfgCutissuanceSzlineViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int CUTISSUEID = AttributesEnum.CutissueId.index();
    public static final int CUTISSUENO = AttributesEnum.CutissueNo.index();
    public static final int SZLINENO = AttributesEnum.SzlineNo.index();
    public static final int SIZEID = AttributesEnum.SizeId.index();
    public static final int BANDELNO = AttributesEnum.BandelNo.index();
    public static final int SHADEID = AttributesEnum.ShadeId.index();
    public static final int SIZBNDID = AttributesEnum.SizBndId.index();
    public static final int PLYFROM = AttributesEnum.PlyFrom.index();
    public static final int PLYTO = AttributesEnum.PlyTo.index();
    public static final int ISSQUANTITY = AttributesEnum.IssQuantity.index();
    public static final int SRQNUMBERFRM = AttributesEnum.SrqNumberFrm.index();
    public static final int SRQNUMBERTO = AttributesEnum.SrqNumberTo.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int TRANSFERQTY = AttributesEnum.TransferQty.index();
    public static final int TOTALQTY = AttributesEnum.TotalQty.index();
    public static final int BALANCEQTY = AttributesEnum.BalanceQty.index();
    public static final int CUTISSUELINEID = AttributesEnum.CutissueLineId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgCutissuanceSzlineViewRowImpl() {
    }

    /**
     * Gets MnjMfgCutissuanceSzline entity object.
     * @return the MnjMfgCutissuanceSzline
     */
    public MnjMfgCutissuanceSzlineImpl getMnjMfgCutissuanceSzline() {
        return (MnjMfgCutissuanceSzlineImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DIVISION_ID using the alias name DivisionId.
     * @return the DIVISION_ID
     */
    public String getDivisionId() {
        return (String) getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION_ID using the alias name DivisionId.
     * @param value value to set the DIVISION_ID
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for CUTISSUE_ID using the alias name CutissueId.
     * @return the CUTISSUE_ID
     */
    public Number getCutissueId() {
        return (Number) getAttributeInternal(CUTISSUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTISSUE_ID using the alias name CutissueId.
     * @param value value to set the CUTISSUE_ID
     */
    public void setCutissueId(Number value) {
        setAttributeInternal(CUTISSUEID, value);
    }

    /**
     * Gets the attribute value for CUTISSUE_NO using the alias name CutissueNo.
     * @return the CUTISSUE_NO
     */
    public Number getCutissueNo() {
        return (Number) getAttributeInternal(CUTISSUENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTISSUE_NO using the alias name CutissueNo.
     * @param value value to set the CUTISSUE_NO
     */
    public void setCutissueNo(Number value) {
        setAttributeInternal(CUTISSUENO, value);
    }

    /**
     * Gets the attribute value for SZLINE_NO using the alias name SzlineNo.
     * @return the SZLINE_NO
     */
    public Number getSzlineNo() {
        return (Number) getAttributeInternal(SZLINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for SZLINE_NO using the alias name SzlineNo.
     * @param value value to set the SZLINE_NO
     */
    public void setSzlineNo(Number value) {
        setAttributeInternal(SZLINENO, value);
    }

    /**
     * Gets the attribute value for SIZE_ID using the alias name SizeId.
     * @return the SIZE_ID
     */
    public String getSizeId() {
        return (String) getAttributeInternal(SIZEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZE_ID using the alias name SizeId.
     * @param value value to set the SIZE_ID
     */
    public void setSizeId(String value) {
        setAttributeInternal(SIZEID, value);
    }

    /**
     * Gets the attribute value for BANDEL_NO using the alias name BandelNo.
     * @return the BANDEL_NO
     */
    public String getBandelNo() {
        return (String) getAttributeInternal(BANDELNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BANDEL_NO using the alias name BandelNo.
     * @param value value to set the BANDEL_NO
     */
    public void setBandelNo(String value) {
        setAttributeInternal(BANDELNO, value);
    }

    /**
     * Gets the attribute value for SHADE_ID using the alias name ShadeId.
     * @return the SHADE_ID
     */
    public String getShadeId() {
        return (String) getAttributeInternal(SHADEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SHADE_ID using the alias name ShadeId.
     * @param value value to set the SHADE_ID
     */
    public void setShadeId(String value) {
        setAttributeInternal(SHADEID, value);
    }

    /**
     * Gets the attribute value for SIZ_BND_ID using the alias name SizBndId.
     * @return the SIZ_BND_ID
     */
    public String getSizBndId() {
        return (String) getAttributeInternal(SIZBNDID);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZ_BND_ID using the alias name SizBndId.
     * @param value value to set the SIZ_BND_ID
     */
    public void setSizBndId(String value) {
        setAttributeInternal(SIZBNDID, value);
    }

    /**
     * Gets the attribute value for PLY_FROM using the alias name PlyFrom.
     * @return the PLY_FROM
     */
    public Number getPlyFrom() {
        return (Number) getAttributeInternal(PLYFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for PLY_FROM using the alias name PlyFrom.
     * @param value value to set the PLY_FROM
     */
    public void setPlyFrom(Number value) {
        setAttributeInternal(PLYFROM, value);
    }

    /**
     * Gets the attribute value for PLY_TO using the alias name PlyTo.
     * @return the PLY_TO
     */
    public Number getPlyTo() {
        return (Number) getAttributeInternal(PLYTO);
    }

    /**
     * Sets <code>value</code> as attribute value for PLY_TO using the alias name PlyTo.
     * @param value value to set the PLY_TO
     */
    public void setPlyTo(Number value) {
        setAttributeInternal(PLYTO, value);
    }

    /**
     * Gets the attribute value for ISS_QUANTITY using the alias name IssQuantity.
     * @return the ISS_QUANTITY
     */
    public Number getIssQuantity() {
        return (Number) getAttributeInternal(ISSQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for ISS_QUANTITY using the alias name IssQuantity.
     * @param value value to set the ISS_QUANTITY
     */
    public void setIssQuantity(Number value) {
        setAttributeInternal(ISSQUANTITY, value);
    }

    /**
     * Gets the attribute value for SRQ_NUMBER_FRM using the alias name SrqNumberFrm.
     * @return the SRQ_NUMBER_FRM
     */
    public Number getSrqNumberFrm() {
        return (Number) getAttributeInternal(SRQNUMBERFRM);
    }

    /**
     * Sets <code>value</code> as attribute value for SRQ_NUMBER_FRM using the alias name SrqNumberFrm.
     * @param value value to set the SRQ_NUMBER_FRM
     */
    public void setSrqNumberFrm(Number value) {
        setAttributeInternal(SRQNUMBERFRM, value);
    }

    /**
     * Gets the attribute value for SRQ_NUMBER_TO using the alias name SrqNumberTo.
     * @return the SRQ_NUMBER_TO
     */
    public Number getSrqNumberTo() {
        return (Number) getAttributeInternal(SRQNUMBERTO);
    }

    /**
     * Sets <code>value</code> as attribute value for SRQ_NUMBER_TO using the alias name SrqNumberTo.
     * @param value value to set the SRQ_NUMBER_TO
     */
    public void setSrqNumberTo(Number value) {
        setAttributeInternal(SRQNUMBERTO, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for TRANSFER_QTY using the alias name TransferQty.
     * @return the TRANSFER_QTY
     */
    public Number getTransferQty() {
        return (Number) getAttributeInternal(TRANSFERQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFER_QTY using the alias name TransferQty.
     * @param value value to set the TRANSFER_QTY
     */
    public void setTransferQty(Number value) {
        setAttributeInternal(TRANSFERQTY, value);
    }

    /**
     * Gets the attribute value for TOTAL_QTY using the alias name TotalQty.
     * @return the TOTAL_QTY
     */
    public Number getTotalQty() {
        return (Number) getAttributeInternal(TOTALQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_QTY using the alias name TotalQty.
     * @param value value to set the TOTAL_QTY
     */
    public void setTotalQty(Number value) {
        setAttributeInternal(TOTALQTY, value);
    }

    /**
     * Gets the attribute value for BALANCE_QTY using the alias name BalanceQty.
     * @return the BALANCE_QTY
     */
    public Number getBalanceQty() {
        return (Number) getAttributeInternal(BALANCEQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for BALANCE_QTY using the alias name BalanceQty.
     * @param value value to set the BALANCE_QTY
     */
    public void setBalanceQty(Number value) {
        setAttributeInternal(BALANCEQTY, value);
    }

    /**
     * Gets the attribute value for CUTISSUE_LINE_ID using the alias name CutissueLineId.
     * @return the CUTISSUE_LINE_ID
     */
    public Number getCutissueLineId() {
        return (Number) getAttributeInternal(CUTISSUELINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTISSUE_LINE_ID using the alias name CutissueLineId.
     * @param value value to set the CUTISSUE_LINE_ID
     */
    public void setCutissueLineId(Number value) {
        setAttributeInternal(CUTISSUELINEID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
