package mnj.mfg.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 29 13:12:29 BDT 2015
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void populateBundles();

    void setPopUpWhereClause();

    void selectAllLines(String flag);

    String getUnitName(String orgId);

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);

    void populateBundlesRec();

    void setPopUpWhereClauseRec();

    void setPopUpWhereClauseThirdParty();

    void populateBundlesThirdParty();

    String CreateRequisition();
}
