package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 13 09:23:49 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CunNumberLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CunNumberLOVImpl() {
    }

    /**
     * Returns the bind variable value for p_trans_type.
     * @return bind variable value for p_trans_type
     */
    public String getp_trans_type() {
        return (String)getNamedWhereClauseParam("p_trans_type");
    }

    /**
     * Sets <code>value</code> for bind variable p_trans_type.
     * @param value value to bind as p_trans_type
     */
    public void setp_trans_type(String value) {
        setNamedWhereClauseParam("p_trans_type", value);
    }

    /**
     * Returns the bind variable value for p_cutplanno.
     * @return bind variable value for p_cutplanno
     */
    public String getp_cutplanno() {
        return (String)getNamedWhereClauseParam("p_cutplanno");
    }

    /**
     * Sets <code>value</code> for bind variable p_cutplanno.
     * @param value value to bind as p_cutplanno
     */
    public void setp_cutplanno(String value) {
        setNamedWhereClauseParam("p_cutplanno", value);
    }
}
