package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 06 15:33:41 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecBundleVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RecBundleVOImpl() {
    }
}
