package mnj.mfg.model.entities;

import java.math.BigDecimal;

import java.sql.SQLException;

import java.util.Map;

import javax.faces.application.FacesMessage;

import javax.faces.context.FacesContext;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 26 17:01:31 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgCutissuanceImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        CutissueId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getCutissueId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setCutissueId((Number)value);
            }
        }
        ,
        CutissueNo {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getCutissueNo();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setCutissueNo((String)value);
            }
        }
        ,
        RangeId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getRangeId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setRangeId((Number)value);
            }
        }
        ,
        RangeNumber {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getRangeNumber();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setRangeNumber((Number)value);
            }
        }
        ,
        SalesorderId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        SoLine {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getSoLine();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setSoLine((Number)value);
            }
        }
        ,
        FgitemCode {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getFgitemCode();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setFgitemCode((String)value);
            }
        }
        ,
        InseamId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getInseamId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setInseamId((String)value);
            }
        }
        ,
        CutjobId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getCutjobId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setCutjobId((String)value);
            }
        }
        ,
        LineNo {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getLineNo();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setLineNo((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CutissueDt {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getCutissueDt();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setCutissueDt((Date)value);
            }
        }
        ,
        CutAssemId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getCutAssemId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setCutAssemId((String)value);
            }
        }
        ,
        StitchJobId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getStitchJobId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setStitchJobId((String)value);
            }
        }
        ,
        StitchAssemId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getStitchAssemId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setStitchAssemId((String)value);
            }
        }
        ,
        OeSolineId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getOeSolineId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setOeSolineId((Number)value);
            }
        }
        ,
        Obno {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getObno();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setObno((String)value);
            }
        }
        ,
        PostedStatus {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getPostedStatus();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setPostedStatus((String)value);
            }
        }
        ,
        CutfrmDivisionId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getCutfrmDivisionId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setCutfrmDivisionId((Number)value);
            }
        }
        ,
        LotNumber {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getLotNumber();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setLotNumber((String)value);
            }
        }
        ,
        TransactionStatus {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getTransactionStatus();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setTransactionStatus((String)value);
            }
        }
        ,
        SubInventory {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getSubInventory();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setSubInventory((String)value);
            }
        }
        ,
        RangrefNo {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getRangrefNo();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setRangrefNo((String)value);
            }
        }
        ,
        PostedStatusTmp {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getPostedStatusTmp();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setPostedStatusTmp((String)value);
            }
        }
        ,
        CuttFromDivid {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getCuttFromDivid();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setCuttFromDivid((String)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        BpoNo {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getBpoNo();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        OrderQty {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getOrderQty();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        CutNumber {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getCutNumber();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setCutNumber((String)value);
            }
        }
        ,
        Color {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getColor();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        IssueTo {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getIssueTo();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setIssueTo((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        RationNo {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getRationNo();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setRationNo((String)value);
            }
        }
        ,
        DeliveryChallanNo {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getDeliveryChallanNo();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setDeliveryChallanNo((String)value);
            }
        }
        ,
        RefDocNo {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getRefDocNo();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setRefDocNo((String)value);
            }
        }
        ,
        IssueToOrg {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getIssueToOrg();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setIssueToOrg((Number)value);
            }
        }
        ,
        ThirdParty {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getThirdParty();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setThirdParty((String)value);
            }
        }
        ,
        ReceiveType {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getReceiveType();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setReceiveType((String)value);
            }
        }
        ,
        RecDocNo {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getRecDocNo();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setRecDocNo((String)value);
            }
        }
        ,
        SystemId {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getSystemId();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setSystemId((BigDecimal)value);
            }
        }
        ,
        MnjMfgCutissuanceSzline {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getMnjMfgCutissuanceSzline();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LineEO {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getLineEO();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LineEO1 {
            public Object get(MnjMfgCutissuanceImpl obj) {
                return obj.getLineEO1();
            }

            public void put(MnjMfgCutissuanceImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgCutissuanceImpl object);

        public abstract void put(MnjMfgCutissuanceImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int CUTISSUEID = AttributesEnum.CutissueId.index();
    public static final int CUTISSUENO = AttributesEnum.CutissueNo.index();
    public static final int RANGEID = AttributesEnum.RangeId.index();
    public static final int RANGENUMBER = AttributesEnum.RangeNumber.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int SOLINE = AttributesEnum.SoLine.index();
    public static final int FGITEMCODE = AttributesEnum.FgitemCode.index();
    public static final int INSEAMID = AttributesEnum.InseamId.index();
    public static final int CUTJOBID = AttributesEnum.CutjobId.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CUTISSUEDT = AttributesEnum.CutissueDt.index();
    public static final int CUTASSEMID = AttributesEnum.CutAssemId.index();
    public static final int STITCHJOBID = AttributesEnum.StitchJobId.index();
    public static final int STITCHASSEMID = AttributesEnum.StitchAssemId.index();
    public static final int OESOLINEID = AttributesEnum.OeSolineId.index();
    public static final int OBNO = AttributesEnum.Obno.index();
    public static final int POSTEDSTATUS = AttributesEnum.PostedStatus.index();
    public static final int CUTFRMDIVISIONID = AttributesEnum.CutfrmDivisionId.index();
    public static final int LOTNUMBER = AttributesEnum.LotNumber.index();
    public static final int TRANSACTIONSTATUS = AttributesEnum.TransactionStatus.index();
    public static final int SUBINVENTORY = AttributesEnum.SubInventory.index();
    public static final int RANGREFNO = AttributesEnum.RangrefNo.index();
    public static final int POSTEDSTATUSTMP = AttributesEnum.PostedStatusTmp.index();
    public static final int CUTTFROMDIVID = AttributesEnum.CuttFromDivid.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int CUTNUMBER = AttributesEnum.CutNumber.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int ISSUETO = AttributesEnum.IssueTo.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int RATIONNO = AttributesEnum.RationNo.index();
    public static final int DELIVERYCHALLANNO = AttributesEnum.DeliveryChallanNo.index();
    public static final int REFDOCNO = AttributesEnum.RefDocNo.index();
    public static final int ISSUETOORG = AttributesEnum.IssueToOrg.index();
    public static final int THIRDPARTY = AttributesEnum.ThirdParty.index();
    public static final int RECEIVETYPE = AttributesEnum.ReceiveType.index();
    public static final int RECDOCNO = AttributesEnum.RecDocNo.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int MNJMFGCUTISSUANCESZLINE = AttributesEnum.MnjMfgCutissuanceSzline.index();
    public static final int LINEEO = AttributesEnum.LineEO.index();
    public static final int LINEEO1 = AttributesEnum.LineEO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgCutissuanceImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgCutissuance");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for CutissueId, using the alias name CutissueId.
     * @return the CutissueId
     */
    public Number getCutissueId() {
        return (Number)getAttributeInternal(CUTISSUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutissueId.
     * @param value value to set the CutissueId
     */
    public void setCutissueId(Number value) {
        setAttributeInternal(CUTISSUEID, value);
    }

    /**
     * Gets the attribute value for CutissueNo, using the alias name CutissueNo.
     * @return the CutissueNo
     */
    public String getCutissueNo() {
        return (String)getAttributeInternal(CUTISSUENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutissueNo.
     * @param value value to set the CutissueNo
     */
    public void setCutissueNo(String value) {
        setAttributeInternal(CUTISSUENO, value);
    }

    /**
     * Gets the attribute value for RangeId, using the alias name RangeId.
     * @return the RangeId
     */
    public Number getRangeId() {
        return (Number)getAttributeInternal(RANGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeId.
     * @param value value to set the RangeId
     */
    public void setRangeId(Number value) {
        setAttributeInternal(RANGEID, value);
    }

    /**
     * Gets the attribute value for RangeNumber, using the alias name RangeNumber.
     * @return the RangeNumber
     */
    public Number getRangeNumber() {
        return (Number)getAttributeInternal(RANGENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangeNumber.
     * @param value value to set the RangeNumber
     */
    public void setRangeNumber(Number value) {
        setAttributeInternal(RANGENUMBER, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public Number getSalesorderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SoLine, using the alias name SoLine.
     * @return the SoLine
     */
    public Number getSoLine() {
        return (Number)getAttributeInternal(SOLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoLine.
     * @param value value to set the SoLine
     */
    public void setSoLine(Number value) {
        setAttributeInternal(SOLINE, value);
    }

    /**
     * Gets the attribute value for FgitemCode, using the alias name FgitemCode.
     * @return the FgitemCode
     */
    public String getFgitemCode() {
        return (String)getAttributeInternal(FGITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FgitemCode.
     * @param value value to set the FgitemCode
     */
    public void setFgitemCode(String value) {
        setAttributeInternal(FGITEMCODE, value);
    }

    /**
     * Gets the attribute value for InseamId, using the alias name InseamId.
     * @return the InseamId
     */
    public String getInseamId() {
        return (String)getAttributeInternal(INSEAMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InseamId.
     * @param value value to set the InseamId
     */
    public void setInseamId(String value) {
        setAttributeInternal(INSEAMID, value);
    }

    /**
     * Gets the attribute value for CutjobId, using the alias name CutjobId.
     * @return the CutjobId
     */
    public String getCutjobId() {
        return (String)getAttributeInternal(CUTJOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutjobId.
     * @param value value to set the CutjobId
     */
    public void setCutjobId(String value) {
        setAttributeInternal(CUTJOBID, value);
    }

    /**
     * Gets the attribute value for LineNo, using the alias name LineNo.
     * @return the LineNo
     */
    public String getLineNo() {
        return (String)getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineNo.
     * @param value value to set the LineNo
     */
    public void setLineNo(String value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CutissueDt, using the alias name CutissueDt.
     * @return the CutissueDt
     */
    public Date getCutissueDt() {
        return (Date)getAttributeInternal(CUTISSUEDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutissueDt.
     * @param value value to set the CutissueDt
     */
    public void setCutissueDt(Date value) {
        setAttributeInternal(CUTISSUEDT, value);
    }

    /**
     * Gets the attribute value for CutAssemId, using the alias name CutAssemId.
     * @return the CutAssemId
     */
    public String getCutAssemId() {
        return (String)getAttributeInternal(CUTASSEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutAssemId.
     * @param value value to set the CutAssemId
     */
    public void setCutAssemId(String value) {
        setAttributeInternal(CUTASSEMID, value);
    }

    /**
     * Gets the attribute value for StitchJobId, using the alias name StitchJobId.
     * @return the StitchJobId
     */
    public String getStitchJobId() {
        return (String)getAttributeInternal(STITCHJOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StitchJobId.
     * @param value value to set the StitchJobId
     */
    public void setStitchJobId(String value) {
        setAttributeInternal(STITCHJOBID, value);
    }

    /**
     * Gets the attribute value for StitchAssemId, using the alias name StitchAssemId.
     * @return the StitchAssemId
     */
    public String getStitchAssemId() {
        return (String)getAttributeInternal(STITCHASSEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StitchAssemId.
     * @param value value to set the StitchAssemId
     */
    public void setStitchAssemId(String value) {
        setAttributeInternal(STITCHASSEMID, value);
    }

    /**
     * Gets the attribute value for OeSolineId, using the alias name OeSolineId.
     * @return the OeSolineId
     */
    public Number getOeSolineId() {
        return (Number)getAttributeInternal(OESOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OeSolineId.
     * @param value value to set the OeSolineId
     */
    public void setOeSolineId(Number value) {
        setAttributeInternal(OESOLINEID, value);
    }

    /**
     * Gets the attribute value for Obno, using the alias name Obno.
     * @return the Obno
     */
    public String getObno() {
        return (String)getAttributeInternal(OBNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Obno.
     * @param value value to set the Obno
     */
    public void setObno(String value) {
        setAttributeInternal(OBNO, value);
    }

    /**
     * Gets the attribute value for PostedStatus, using the alias name PostedStatus.
     * @return the PostedStatus
     */
    public String getPostedStatus() {
        return (String)getAttributeInternal(POSTEDSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostedStatus.
     * @param value value to set the PostedStatus
     */
    public void setPostedStatus(String value) {
        setAttributeInternal(POSTEDSTATUS, value);
    }

    /**
     * Gets the attribute value for CutfrmDivisionId, using the alias name CutfrmDivisionId.
     * @return the CutfrmDivisionId
     */
    public Number getCutfrmDivisionId() {
        return (Number)getAttributeInternal(CUTFRMDIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutfrmDivisionId.
     * @param value value to set the CutfrmDivisionId
     */
    public void setCutfrmDivisionId(Number value) {
        setAttributeInternal(CUTFRMDIVISIONID, value);
    }

    /**
     * Gets the attribute value for LotNumber, using the alias name LotNumber.
     * @return the LotNumber
     */
    public String getLotNumber() {
        return (String)getAttributeInternal(LOTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for LotNumber.
     * @param value value to set the LotNumber
     */
    public void setLotNumber(String value) {
        setAttributeInternal(LOTNUMBER, value);
    }

    /**
     * Gets the attribute value for TransactionStatus, using the alias name TransactionStatus.
     * @return the TransactionStatus
     */
    public String getTransactionStatus() {
        return (String)getAttributeInternal(TRANSACTIONSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionStatus.
     * @param value value to set the TransactionStatus
     */
    public void setTransactionStatus(String value) {
        setAttributeInternal(TRANSACTIONSTATUS, value);
    }

    /**
     * Gets the attribute value for SubInventory, using the alias name SubInventory.
     * @return the SubInventory
     */
    public String getSubInventory() {
        return (String)getAttributeInternal(SUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubInventory.
     * @param value value to set the SubInventory
     */
    public void setSubInventory(String value) {
        setAttributeInternal(SUBINVENTORY, value);
    }

    /**
     * Gets the attribute value for RangrefNo, using the alias name RangrefNo.
     * @return the RangrefNo
     */
    public String getRangrefNo() {
        return (String)getAttributeInternal(RANGREFNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RangrefNo.
     * @param value value to set the RangrefNo
     */
    public void setRangrefNo(String value) {
        setAttributeInternal(RANGREFNO, value);
    }

    /**
     * Gets the attribute value for PostedStatusTmp, using the alias name PostedStatusTmp.
     * @return the PostedStatusTmp
     */
    public String getPostedStatusTmp() {
        return (String)getAttributeInternal(POSTEDSTATUSTMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostedStatusTmp.
     * @param value value to set the PostedStatusTmp
     */
    public void setPostedStatusTmp(String value) {
        setAttributeInternal(POSTEDSTATUSTMP, value);
    }

    /**
     * Gets the attribute value for CuttFromDivid, using the alias name CuttFromDivid.
     * @return the CuttFromDivid
     */
    public String getCuttFromDivid() {
        return (String)getAttributeInternal(CUTTFROMDIVID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CuttFromDivid.
     * @param value value to set the CuttFromDivid
     */
    public void setCuttFromDivid(String value) {
        setAttributeInternal(CUTTFROMDIVID, value);
    }

    /**
     * Gets the attribute value for InventoryItemId, using the alias name InventoryItemId.
     * @return the InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number)getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryItemId.
     * @param value value to set the InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }


    /**
     * Gets the attribute value for BpoNo, using the alias name BpoNo.
     * @return the BpoNo
     */
    public String getBpoNo() {
        return (String)getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoNo.
     * @param value value to set the BpoNo
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for OrderQty, using the alias name OrderQty.
     * @return the OrderQty
     */
    public Number getOrderQty() {
        return (Number)getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQty.
     * @param value value to set the OrderQty
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }


    /**
     * Gets the attribute value for CutNumber, using the alias name CutNumber.
     * @return the CutNumber
     */
    public String getCutNumber() {
        return (String)getAttributeInternal(CUTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutNumber.
     * @param value value to set the CutNumber
     */
    public void setCutNumber(String value) {
        setAttributeInternal(CUTNUMBER, value);
    }

    /**
     * Gets the attribute value for Color, using the alias name Color.
     * @return the Color
     */
    public String getColor() {
        return (String)getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Color.
     * @param value value to set the Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for IssueTo, using the alias name IssueTo.
     * @return the IssueTo
     */
    public String getIssueTo() {
        return (String)getAttributeInternal(ISSUETO);
    }

    /**
     * Sets <code>value</code> as the attribute value for IssueTo.
     * @param value value to set the IssueTo
     */
    public void setIssueTo(String value) {
        setAttributeInternal(ISSUETO, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for RationNo, using the alias name RationNo.
     * @return the RationNo
     */
    public String getRationNo() {
        return (String)getAttributeInternal(RATIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RationNo.
     * @param value value to set the RationNo
     */
    public void setRationNo(String value) {
        setAttributeInternal(RATIONNO, value);
    }

    /**
     * Gets the attribute value for DeliveryChallanNo, using the alias name DeliveryChallanNo.
     * @return the DeliveryChallanNo
     */
    public String getDeliveryChallanNo() {
        return (String)getAttributeInternal(DELIVERYCHALLANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryChallanNo.
     * @param value value to set the DeliveryChallanNo
     */
    public void setDeliveryChallanNo(String value) {
        setAttributeInternal(DELIVERYCHALLANNO, value);
    }

    /**
     * Gets the attribute value for RefDocNo, using the alias name RefDocNo.
     * @return the RefDocNo
     */
    public String getRefDocNo() {
        return (String)getAttributeInternal(REFDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefDocNo.
     * @param value value to set the RefDocNo
     */
    public void setRefDocNo(String value) {
        setAttributeInternal(REFDOCNO, value);
    }

    /**
     * Gets the attribute value for IssueToOrg, using the alias name IssueToOrg.
     * @return the IssueToOrg
     */
    public Number getIssueToOrg() {
        return (Number)getAttributeInternal(ISSUETOORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for IssueToOrg.
     * @param value value to set the IssueToOrg
     */
    public void setIssueToOrg(Number value) {
        setAttributeInternal(ISSUETOORG, value);
    }

    /**
     * Gets the attribute value for ThirdParty, using the alias name ThirdParty.
     * @return the ThirdParty
     */
    public String getThirdParty() {
        return (String)getAttributeInternal(THIRDPARTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ThirdParty.
     * @param value value to set the ThirdParty
     */
    public void setThirdParty(String value) {
        setAttributeInternal(THIRDPARTY, value);
    }

    /**
     * Gets the attribute value for ReceiveType, using the alias name ReceiveType.
     * @return the ReceiveType
     */
    public String getReceiveType() {
        return (String)getAttributeInternal(RECEIVETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceiveType.
     * @param value value to set the ReceiveType
     */
    public void setReceiveType(String value) {
        setAttributeInternal(RECEIVETYPE, value);
    }

    /**
     * Gets the attribute value for RecDocNo, using the alias name RecDocNo.
     * @return the RecDocNo
     */
    public String getRecDocNo() {
        return (String)getAttributeInternal(RECDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RecDocNo.
     * @param value value to set the RecDocNo
     */
    public void setRecDocNo(String value) {
        setAttributeInternal(RECDOCNO, value);
    }

    /**
     * Gets the attribute value for SystemId, using the alias name SystemId.
     * @return the SystemId
     */
    public BigDecimal getSystemId() {
        return (BigDecimal)getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SystemId.
     * @param value value to set the SystemId
     */
    public void setSystemId(BigDecimal value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgCutissuanceSzline() {
        return (RowIterator)getAttributeInternal(MNJMFGCUTISSUANCESZLINE);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getLineEO() {
        return (RowIterator)getAttributeInternal(LINEEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getLineEO1() {
        return (RowIterator)getAttributeInternal(LINEEO1);
    }


    /**
     * @param cutissueId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number cutissueId) {
        return new Key(new Object[]{cutissueId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("MNJ_MFG_CUTISSUANCE_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setCutissueId(sVal);
       

    }

    public String getSrNoString() {
        String srno = null;
        String stmt = "BEGIN :1 := mnj_mfg_doc_no_pkg.cut_issueto_stitch_srno; end;";
        java.sql.CallableStatement cs =
            getDBTransaction().createCallableStatement(stmt, 1);
        try {
            cs.registerOutParameter(1, oracle.jdbc.OracleTypes.VARCHAR);
            cs.execute();
            srno = cs.getString(1);
            cs.close();
            System.out.println(srno+"srno--->"+srno);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return srno;
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {

        ViewObject vo =
            getDBTransaction().createViewObjectFromQueryStmt("select count(1) from MNJ_MFG_CUTISSUANCE_SZLINE h where h.CUTISSUE_ID =" +
                                                             getCutissueId());
        vo.first();
        int count = 0;
        try {
            count =
                    Integer.parseInt(vo.getCurrentRow().getAttribute(0).toString());
        } catch (Exception e) {
            vo.remove();
        }
        if (count == 0) {
            super.remove();
        } else {
            String messageText = "Child Records exists , can't delete";
            FacesMessage fm = new FacesMessage(messageText);
            fm.setSeverity(FacesMessage.SEVERITY_INFO);
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, fm);

        } //end of else
        vo.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
     protected void doDML(int operation, TransactionEvent e) {
         Map sessionScope = ADFContext.getCurrent().getSessionScope();   
         String user = (String)sessionScope.get("userId");
         String orgId  =(String)sessionScope.get("orgId");
         String unitName  =(String)sessionScope.get("unitName");
        
         System.out.println("ASSES INS DO DML 1 ------------------>"+user);
         System.out.println("ASSES INS DO DML 2------------------>"+orgId);
         System.out.println("ASSES INS DML 3 ------------------>"+unitName);
         
         if(DML_UPDATE == operation){
                   try {
                       setLastUpdateDate((Date)Date.getCurrentDate()); 
                       setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                   } catch (SQLException f) {
                       System.out.println(f.getMessage());
                   }
               }
               else if (DML_INSERT == operation){
                
                   try {
                       setCutissueNo(getSrNoString());
                       setDivisionId(orgId);
                       setAttribute1(unitName);
                       setCreationDate((Date)Date.getCurrentDate());  
                       setCreatedBy(new oracle.jbo.domain.Number(user));
                      
                      
                      
                   } catch (SQLException f) {
                       ;
                   }
               }
         
         super.doDML(operation, e);
     }
}
