package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 26 17:04:37 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgCutissuanceSzlineImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        CutissueId {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getCutissueId();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setCutissueId((Number)value);
            }
        }
        ,
        CutissueNo {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getCutissueNo();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setCutissueNo((Number)value);
            }
        }
        ,
        SzlineNo {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getSzlineNo();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setSzlineNo((Number)value);
            }
        }
        ,
        SizeId {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getSizeId();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setSizeId((String)value);
            }
        }
        ,
        BandelNo {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getBandelNo();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setBandelNo((String)value);
            }
        }
        ,
        ShadeId {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getShadeId();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setShadeId((String)value);
            }
        }
        ,
        SizBndId {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getSizBndId();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setSizBndId((String)value);
            }
        }
        ,
        PlyFrom {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getPlyFrom();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setPlyFrom((Number)value);
            }
        }
        ,
        PlyTo {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getPlyTo();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setPlyTo((Number)value);
            }
        }
        ,
        IssQuantity {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getIssQuantity();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setIssQuantity((Number)value);
            }
        }
        ,
        SrqNumberFrm {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getSrqNumberFrm();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setSrqNumberFrm((Number)value);
            }
        }
        ,
        SrqNumberTo {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getSrqNumberTo();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setSrqNumberTo((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        TransferQty {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getTransferQty();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setTransferQty((Number)value);
            }
        }
        ,
        TotalQty {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getTotalQty();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setTotalQty((Number)value);
            }
        }
        ,
        BalanceQty {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getBalanceQty();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setBalanceQty((Number)value);
            }
        }
        ,
        CutissueLineId {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getCutissueLineId();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setCutissueLineId((Number)value);
            }
        }
        ,
        MnjMfgCutissuance {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getMnjMfgCutissuance();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setMnjMfgCutissuance((MnjMfgCutissuanceImpl)value);
            }
        }
        ,
        LineEO {
            public Object get(MnjMfgCutissuanceSzlineImpl obj) {
                return obj.getLineEO();
            }

            public void put(MnjMfgCutissuanceSzlineImpl obj, Object value) {
                obj.setLineEO((LineEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgCutissuanceSzlineImpl object);

        public abstract void put(MnjMfgCutissuanceSzlineImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int CUTISSUEID = AttributesEnum.CutissueId.index();
    public static final int CUTISSUENO = AttributesEnum.CutissueNo.index();
    public static final int SZLINENO = AttributesEnum.SzlineNo.index();
    public static final int SIZEID = AttributesEnum.SizeId.index();
    public static final int BANDELNO = AttributesEnum.BandelNo.index();
    public static final int SHADEID = AttributesEnum.ShadeId.index();
    public static final int SIZBNDID = AttributesEnum.SizBndId.index();
    public static final int PLYFROM = AttributesEnum.PlyFrom.index();
    public static final int PLYTO = AttributesEnum.PlyTo.index();
    public static final int ISSQUANTITY = AttributesEnum.IssQuantity.index();
    public static final int SRQNUMBERFRM = AttributesEnum.SrqNumberFrm.index();
    public static final int SRQNUMBERTO = AttributesEnum.SrqNumberTo.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int TRANSFERQTY = AttributesEnum.TransferQty.index();
    public static final int TOTALQTY = AttributesEnum.TotalQty.index();
    public static final int BALANCEQTY = AttributesEnum.BalanceQty.index();
    public static final int CUTISSUELINEID = AttributesEnum.CutissueLineId.index();
    public static final int MNJMFGCUTISSUANCE = AttributesEnum.MnjMfgCutissuance.index();
    public static final int LINEEO = AttributesEnum.LineEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgCutissuanceSzlineImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgCutissuanceSzline");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for CutissueId, using the alias name CutissueId.
     * @return the CutissueId
     */
    public Number getCutissueId() {
        return (Number)getAttributeInternal(CUTISSUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutissueId.
     * @param value value to set the CutissueId
     */
    public void setCutissueId(Number value) {
        setAttributeInternal(CUTISSUEID, value);
    }

    /**
     * Gets the attribute value for CutissueNo, using the alias name CutissueNo.
     * @return the CutissueNo
     */
    public Number getCutissueNo() {
        return (Number)getAttributeInternal(CUTISSUENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutissueNo.
     * @param value value to set the CutissueNo
     */
    public void setCutissueNo(Number value) {
        setAttributeInternal(CUTISSUENO, value);
    }

    /**
     * Gets the attribute value for SzlineNo, using the alias name SzlineNo.
     * @return the SzlineNo
     */
    public Number getSzlineNo() {
        return (Number)getAttributeInternal(SZLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SzlineNo.
     * @param value value to set the SzlineNo
     */
    public void setSzlineNo(Number value) {
        setAttributeInternal(SZLINENO, value);
    }

    /**
     * Gets the attribute value for SizeId, using the alias name SizeId.
     * @return the SizeId
     */
    public String getSizeId() {
        return (String)getAttributeInternal(SIZEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeId.
     * @param value value to set the SizeId
     */
    public void setSizeId(String value) {
        setAttributeInternal(SIZEID, value);
    }

    /**
     * Gets the attribute value for BandelNo, using the alias name BandelNo.
     * @return the BandelNo
     */
    public String getBandelNo() {
        return (String)getAttributeInternal(BANDELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BandelNo.
     * @param value value to set the BandelNo
     */
    public void setBandelNo(String value) {
        setAttributeInternal(BANDELNO, value);
    }

    /**
     * Gets the attribute value for ShadeId, using the alias name ShadeId.
     * @return the ShadeId
     */
    public String getShadeId() {
        return (String)getAttributeInternal(SHADEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShadeId.
     * @param value value to set the ShadeId
     */
    public void setShadeId(String value) {
        setAttributeInternal(SHADEID, value);
    }

    /**
     * Gets the attribute value for SizBndId, using the alias name SizBndId.
     * @return the SizBndId
     */
    public String getSizBndId() {
        return (String)getAttributeInternal(SIZBNDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizBndId.
     * @param value value to set the SizBndId
     */
    public void setSizBndId(String value) {
        setAttributeInternal(SIZBNDID, value);
    }

    /**
     * Gets the attribute value for PlyFrom, using the alias name PlyFrom.
     * @return the PlyFrom
     */
    public Number getPlyFrom() {
        return (Number)getAttributeInternal(PLYFROM);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlyFrom.
     * @param value value to set the PlyFrom
     */
    public void setPlyFrom(Number value) {
        setAttributeInternal(PLYFROM, value);
    }

    /**
     * Gets the attribute value for PlyTo, using the alias name PlyTo.
     * @return the PlyTo
     */
    public Number getPlyTo() {
        return (Number)getAttributeInternal(PLYTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlyTo.
     * @param value value to set the PlyTo
     */
    public void setPlyTo(Number value) {
        setAttributeInternal(PLYTO, value);
    }

    /**
     * Gets the attribute value for IssQuantity, using the alias name IssQuantity.
     * @return the IssQuantity
     */
    public Number getIssQuantity() {
        return (Number)getAttributeInternal(ISSQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for IssQuantity.
     * @param value value to set the IssQuantity
     */
    public void setIssQuantity(Number value) {
        setAttributeInternal(ISSQUANTITY, value);
    }

    /**
     * Gets the attribute value for SrqNumberFrm, using the alias name SrqNumberFrm.
     * @return the SrqNumberFrm
     */
    public Number getSrqNumberFrm() {
        return (Number)getAttributeInternal(SRQNUMBERFRM);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrqNumberFrm.
     * @param value value to set the SrqNumberFrm
     */
    public void setSrqNumberFrm(Number value) {
        setAttributeInternal(SRQNUMBERFRM, value);
    }

    /**
     * Gets the attribute value for SrqNumberTo, using the alias name SrqNumberTo.
     * @return the SrqNumberTo
     */
    public Number getSrqNumberTo() {
        return (Number)getAttributeInternal(SRQNUMBERTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrqNumberTo.
     * @param value value to set the SrqNumberTo
     */
    public void setSrqNumberTo(Number value) {
        setAttributeInternal(SRQNUMBERTO, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for TransferQty, using the alias name TransferQty.
     * @return the TransferQty
     */
    public Number getTransferQty() {
        return (Number)getAttributeInternal(TRANSFERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransferQty.
     * @param value value to set the TransferQty
     */
    public void setTransferQty(Number value) {
        setAttributeInternal(TRANSFERQTY, value);
    }

    /**
     * Gets the attribute value for TotalQty, using the alias name TotalQty.
     * @return the TotalQty
     */
    public Number getTotalQty() {
        return (Number)getAttributeInternal(TOTALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalQty.
     * @param value value to set the TotalQty
     */
    public void setTotalQty(Number value) {
        setAttributeInternal(TOTALQTY, value);
    }

    /**
     * Gets the attribute value for BalanceQty, using the alias name BalanceQty.
     * @return the BalanceQty
     */
    public Number getBalanceQty() {
        return (Number)getAttributeInternal(BALANCEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BalanceQty.
     * @param value value to set the BalanceQty
     */
    public void setBalanceQty(Number value) {
        setAttributeInternal(BALANCEQTY, value);
    }

    /**
     * Gets the attribute value for CutissueLineId, using the alias name CutissueLineId.
     * @return the CutissueLineId
     */
    public Number getCutissueLineId() {
        return (Number)getAttributeInternal(CUTISSUELINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutissueLineId.
     * @param value value to set the CutissueLineId
     */
    public void setCutissueLineId(Number value) {
        setAttributeInternal(CUTISSUELINEID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgCutissuanceImpl.
     */
    public MnjMfgCutissuanceImpl getMnjMfgCutissuance() {
        return (MnjMfgCutissuanceImpl)getAttributeInternal(MNJMFGCUTISSUANCE);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgCutissuanceImpl.
     */
    public void setMnjMfgCutissuance(MnjMfgCutissuanceImpl value) {
        setAttributeInternal(MNJMFGCUTISSUANCE, value);
    }


    /**
     * @return the associated entity LineEOImpl.
     */
    public LineEOImpl getLineEO() {
        return (LineEOImpl)getAttributeInternal(LINEEO);
    }

    /**
     * Sets <code>value</code> as the associated entity LineEOImpl.
     */
    public void setLineEO(LineEOImpl value) {
        setAttributeInternal(LINEEO, value);
    }


    /**
     * @param sizeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String sizeId) {
        return new Key(new Object[]{sizeId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_CUTISSUANCE_SZLINE_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setSizeId(String.valueOf(sVal));
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

   
    
    /**
        * Custom DML update/insert/delete logic here.
        * @param operation the operation type
        * @param e the transaction event
        */
       protected void doDML(int operation, TransactionEvent e) {
           Map sessionScope = ADFContext.getCurrent().getSessionScope();   
           String user = (String)sessionScope.get("userId");
           String orgId  =(String)sessionScope.get("orgId");
           String unitName  =(String)sessionScope.get("unitName");
           
           System.out.println("ASSES INS DO DML 1 ------------------>"+user);
           System.out.println("ASSES INS DO DML 2------------------>"+orgId);
           System.out.println("ASSES INS DML 3 ------------------>"+unitName);
           
           if(DML_UPDATE == operation){
                     try {
                         
                         setLastUpdateDate((Date)Date.getCurrentDate()); 
                         setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                     } catch (SQLException f) {
                         System.out.println(f.getMessage());
                     }
                 }
                 else if (DML_INSERT == operation){
                  
                     try {
                         
                         //setHeaderNo(getSrNoString());
                         //setOrgId(new oracle.jbo.domain.Number(orgId));
                         //setAttribute1(unitName);
                         setCreationDate((Date)Date.getCurrentDate());  
                         setCreatedBy(new oracle.jbo.domain.Number(user));
                        
                        
                        
                     } catch (SQLException f) {
                         ;
                     }
                 } 
           
           super.doDML(operation, e);
       }

}
