package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 21 15:18:07 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class cutLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public cutLOVImpl() {
    }

    /**
     * Returns the bind variable value for bpo_no.
     * @return bind variable value for bpo_no
     */
    public String getbpo_no() {
        return (String)getNamedWhereClauseParam("bpo_no");
    }

    /**
     * Sets <code>value</code> for bind variable bpo_no.
     * @param value value to bind as bpo_no
     */
    public void setbpo_no(String value) {
        setNamedWhereClauseParam("bpo_no", value);
    }
}
