package mnj.mfg.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 14 16:08:10 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class cutNumberLOVvORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        TotalPcs {
            public Object get(cutNumberLOVvORowImpl obj) {
                return obj.getTotalPcs();
            }

            public void put(cutNumberLOVvORowImpl obj, Object value) {
                obj.setTotalPcs((Number)value);
            }
        }
        ,
        TotalIssue {
            public Object get(cutNumberLOVvORowImpl obj) {
                return obj.getTotalIssue();
            }

            public void put(cutNumberLOVvORowImpl obj, Object value) {
                obj.setTotalIssue((Number)value);
            }
        }
        ,
        CutNo {
            public Object get(cutNumberLOVvORowImpl obj) {
                return obj.getCutNo();
            }

            public void put(cutNumberLOVvORowImpl obj, Object value) {
                obj.setCutNo((String)value);
            }
        }
        ,
        RatioplanNumber {
            public Object get(cutNumberLOVvORowImpl obj) {
                return obj.getRatioplanNumber();
            }

            public void put(cutNumberLOVvORowImpl obj, Object value) {
                obj.setRatioplanNumber((String)value);
            }
        }
        ,
        MarkerId {
            public Object get(cutNumberLOVvORowImpl obj) {
                return obj.getMarkerId();
            }

            public void put(cutNumberLOVvORowImpl obj, Object value) {
                obj.setMarkerId((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(cutNumberLOVvORowImpl object);

        public abstract void put(cutNumberLOVvORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TOTALPCS = AttributesEnum.TotalPcs.index();
    public static final int TOTALISSUE = AttributesEnum.TotalIssue.index();
    public static final int CUTNO = AttributesEnum.CutNo.index();
    public static final int RATIOPLANNUMBER = AttributesEnum.RatioplanNumber.index();
    public static final int MARKERID = AttributesEnum.MarkerId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public cutNumberLOVvORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CutNo.
     * @return the CutNo
     */
    public String getCutNo() {
        return (String) getAttributeInternal(CUTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CutNo.
     * @param value value to set the  CutNo
     */
    public void setCutNo(String value) {
        setAttributeInternal(CUTNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RatioplanNumber.
     * @return the RatioplanNumber
     */
    public String getRatioplanNumber() {
        return (String) getAttributeInternal(RATIOPLANNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RatioplanNumber.
     * @param value value to set the  RatioplanNumber
     */
    public void setRatioplanNumber(String value) {
        setAttributeInternal(RATIOPLANNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MarkerId.
     * @return the MarkerId
     */
    public String getMarkerId() {
        return (String) getAttributeInternal(MARKERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MarkerId.
     * @param value value to set the  MarkerId
     */
    public void setMarkerId(String value) {
        setAttributeInternal(MARKERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalPcs.
     * @return the TotalPcs
     */
    public Number getTotalPcs() {
        return (Number) getAttributeInternal(TOTALPCS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalPcs.
     * @param value value to set the  TotalPcs
     */
    public void setTotalPcs(Number value) {
        setAttributeInternal(TOTALPCS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalIssue.
     * @return the TotalIssue
     */
    public Number getTotalIssue() {
        return (Number) getAttributeInternal(TOTALISSUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalIssue.
     * @param value value to set the  TotalIssue
     */
    public void setTotalIssue(Number value) {
        setAttributeInternal(TOTALISSUE, value);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
