package mnj.mfg.model.lov.views;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 23 13:15:17 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IssueToStitchLovRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Issuedtostich {
            public Object get(IssueToStitchLovRowImpl obj) {
                return obj.getIssuedtostich();
            }

            public void put(IssueToStitchLovRowImpl obj, Object value) {
                obj.setIssuedtostich((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(IssueToStitchLovRowImpl object);

        public abstract void put(IssueToStitchLovRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ISSUEDTOSTICH = AttributesEnum.Issuedtostich.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IssueToStitchLovRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Issuedtostich.
     * @return the Issuedtostich
     */
    public String getIssuedtostich() {
        return (String) getAttributeInternal(ISSUEDTOSTICH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Issuedtostich.
     * @param value value to set the  Issuedtostich
     */
    public void setIssuedtostich(String value) {
        setAttributeInternal(ISSUEDTOSTICH, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
