package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 23 13:15:17 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IssueToStitchLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IssueToStitchLovImpl() {
    }
}
