package mnj.mfg.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 14 15:41:45 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class rationPlanLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public rationPlanLovImpl() {
    }

    /**
     * Returns the bind variable value for buyer_id.
     * @return bind variable value for buyer_id
     */
    public Number getbuyer_id() {
        return (Number)getNamedWhereClauseParam("buyer_id");
    }

    /**
     * Sets <code>value</code> for bind variable buyer_id.
     * @param value value to bind as buyer_id
     */
    public void setbuyer_id(Number value) {
        setNamedWhereClauseParam("buyer_id", value);
    }

    /**
     * Returns the bind variable value for color.
     * @return bind variable value for color
     */
    public String getcolor() {
        return (String)getNamedWhereClauseParam("color");
    }

    /**
     * Sets <code>value</code> for bind variable color.
     * @param value value to bind as color
     */
    public void setcolor(String value) {
        setNamedWhereClauseParam("color", value);
    }

    /**
     * Returns the bind variable value for season.
     * @return bind variable value for season
     */
    public String getseason() {
        return (String)getNamedWhereClauseParam("season");
    }

    /**
     * Sets <code>value</code> for bind variable season.
     * @param value value to bind as season
     */
    public void setseason(String value) {
        setNamedWhereClauseParam("season", value);
    }

    /**
     * Returns the bind variable value for style.
     * @return bind variable value for style
     */
    public String getstyle() {
        return (String)getNamedWhereClauseParam("style");
    }

    /**
     * Sets <code>value</code> for bind variable style.
     * @param value value to bind as style
     */
    public void setstyle(String value) {
        setNamedWhereClauseParam("style", value);
    }
}
