package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 06 12:48:57 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecTypeLoVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RecTypeLoVImpl() {
    }

    /**
     * Returns the bind variable value for P_REC_TYPE.
     * @return bind variable value for P_REC_TYPE
     */
    public String getP_REC_TYPE() {
        return (String)getNamedWhereClauseParam("P_REC_TYPE");
    }

    /**
     * Sets <code>value</code> for bind variable P_REC_TYPE.
     * @param value value to bind as P_REC_TYPE
     */
    public void setP_REC_TYPE(String value) {
        setNamedWhereClauseParam("P_REC_TYPE", value);
    }
}
