package mnj.mfg.model.lov.views;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 06 12:48:57 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecTypeLoVRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        IssueDoc {
            public Object get(RecTypeLoVRowImpl obj) {
                return obj.getIssueDoc();
            }

            public void put(RecTypeLoVRowImpl obj, Object value) {
                obj.setIssueDoc((String)value);
            }
        }
        ,
        RecType {
            public Object get(RecTypeLoVRowImpl obj) {
                return obj.getRecType();
            }

            public void put(RecTypeLoVRowImpl obj, Object value) {
                obj.setRecType((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(RecTypeLoVRowImpl object);

        public abstract void put(RecTypeLoVRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ISSUEDOC = AttributesEnum.IssueDoc.index();
    public static final int RECTYPE = AttributesEnum.RecType.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RecTypeLoVRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IssueDoc.
     * @return the IssueDoc
     */
    public String getIssueDoc() {
        return (String) getAttributeInternal(ISSUEDOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IssueDoc.
     * @param value value to set the  IssueDoc
     */
    public void setIssueDoc(String value) {
        setAttributeInternal(ISSUEDOC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RecType.
     * @return the RecType
     */
    public String getRecType() {
        return (String) getAttributeInternal(RECTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RecType.
     * @param value value to set the  RecType
     */
    public void setRecType(String value) {
        setAttributeInternal(RECTYPE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
